### ISSUE TITLE
Unable to find Conv Block 

### ISSUE THREAD

**Issue by khawar512** [SHI-Labs/Compact-Transformers#11]
Dear @stevenwalton,

I am trying to find the code block of **Algorithm 1 CCT ConvBlock(PyTorch-style)**. 
Is this code available on paper?

Regards,
Khawar

**Comment by stevenwalton** [comment]
Hi Khawar,

Are you looking for this? https://github.com/SHI-Labs/Compact-Transformers/blob/main/src/cct.py#L31

**Comment by khawar512** [comment]
@stevenwalton I think I am wrong because in a paper you have mentioned a block so I am trying to find the block in your code.

**Comment by stevenwalton** [comment]
We just wrapped them inside the tokenizer class. You could make that set of layers its own class/Module as and include it. Sorry if this was confusing.

**Comment by khawar512** [comment]
@stevenwalton thank you

**Comment by stevenwalton** [comment]
Happy to help!
