### ISSUE TITLE
what is the advantage of CCT Compared with ResNet164 ？？

### ISSUE THREAD

**Issue by Johnson-yue** [SHI-Labs/Compact-Transformers#12]
look at  the Table1 in paper：
![image](https://user-images.githubusercontent.com/10268274/123732819-0e047300-d8cd-11eb-9de7-b5c07f2a05d3.png)

I understand  the CCT model is more parameters and MAC than ResNet164 but with same Acc

**Comment by alihassanijr** [comment]
Hi,

The preprint will be updated within the next day, we actually get better results than you see.

**Comment by Johnson-yue** [comment]
oh，I look forward to the new experiment results ！  thanks your share， when you update the paper plz close this issue

**Comment by alihassanijr** [comment]
Actually you can see the results and the checkpoints in this repo (95.29 on CIFAR-10, 77.05 on CIFAR-100).
