### ISSUE TITLE
Possibility to use CCT Transformer instead of CCT small models

### ISSUE THREAD

**Issue by khawar512** [SHI-Labs/Compact-Transformers#13]
Dear @stevenwalton,

I would like to use the configuration of the best model directly from the CCT Transformer class not calling the model function. I want to directly use the CCT Transformer class like VIT. Like below

https://github.com/lucidrains/vit-pytorch  Please check the VIT model

```
v = ViT(
    image_size = 256,
    patch_size = 32,
    num_classes = 1000,
    dim = 1024,
    depth = 6,
    heads = 16,
    mlp_dim = 2048,
    dropout = 0.1,
    emb_dropout = 0.1
)
```
For CCT
```
"CCT": CCT (
            # GPU_ID=GPU_ID,
            # img_size=112,
            # num_classes=NUM_CLASS,
            positional_embedding='positional_embedding',
            n_conv_layers=2,
            kernel_size=3,
            patch_size=8
        ),
```

**Comment by stevenwalton** [comment]
Hey Khawar

We've discussed incorporating our model into vit-pytorch, but it isn't ready for that yet (will soon). But you should just be able to load it if you include our libraries. You can see how we do it [here](https://github.com/SHI-Labs/Compact-Transformers/blob/main/main.py#L119) in the main file. The dictionary argument just specifies which size model you would want (we follow a torchvision standard for different models). You'll only need `cct.py` in your includes but you'll need `transformers.py` in your path.

**Comment by stevenwalton** [comment]
Hey Khawar, 

we created a [pull request](https://github.com/lucidrains/vit-pytorch/pull/128) with vit-pytorch. I'm going to close this issue and we can monitor the PR over there. Feel free to comment if there are other issues.
