### ISSUE TITLE
Transformer Encoder Code Similarity

### ISSUE THREAD

**Issue by khawar512** [SHI-Labs/Compact-Transformers#14]
Hi @stevenwalton 

What is the difference between your **"TransformerEncoderLayer"** and original Vit paper "Transformer" class?

**Orginal VIT**
```
class Transformer(nn.Module):
    def __init__(self, dim, depth, heads, dim_head, mlp_dim, dropout):
        super().__init__()
        self.layers = nn.ModuleList([])  # There are using Residual
        for _ in range(depth):
            self.layers.append(nn.ModuleList([
                Residual(PreNorm(dim, Attention(dim, heads=heads, dim_head=dim_head, dropout=dropout))),
                # Here they implemented Residual
                Residual(PreNorm(dim, FeedForward(dim, mlp_dim, dropout=dropout)))
            ]))

    def forward(self, x, mask=None):
        for attn, ff in self.layers:
            x = attn(x, mask=mask)  # Chnage in this part
            # embed()
            x = ff(x)
        return x

```
**Your Transformer**

```
class TransformerEncoderLayer(nn.Module):
    """
    Inspired by torch.nn.TransformerEncoderLayer and
    rwightman's timm package.
    """

    def __init__(self, d_model, nhead, dim_feedforward=2048, dropout=0.1,
                 attention_dropout=0.1, drop_path_rate=0.1):
        super(TransformerEncoderLayer, self).__init__()
        self.pre_norm = nn.LayerNorm(d_model)
        self.self_attn = Attention(dim=d_model, num_heads=nhead,
                                   attention_dropout=attention_dropout, projection_dropout=dropout)

        self.linear1 = nn.Linear(d_model, dim_feedforward)
        self.dropout1 = nn.Dropout(dropout)
        self.norm1 = nn.LayerNorm(d_model)
        self.linear2 = nn.Linear(dim_feedforward, d_model)
        self.dropout2 = nn.Dropout(dropout)

        self.drop_path = DropPath(drop_path_rate) if drop_path_rate > 0 else nn.Identity()

        self.activation = F.gelu

    def forward(self, src: torch.Tensor, mask=None, *args, **kwargs) -> torch.Tensor:
        src = src + self.drop_path(self.self_attn(self.pre_norm(src)))
        src = self.norm1(src)
        src2 = self.linear2(self.dropout1(self.activation(self.linear1(src))))
        src = src + self.drop_path(self.dropout2(src2))
        return src
```

Actually, I made some modifications in the original VIT and I want to add that modified part in your Transformer Encoder layer but your's code is different in terms of TransformerEncoderLayer.

**Comment by stevenwalton** [comment]
The transformer encoder layer isn't meaningfully different. The main changes we made were at the beginning (conv blocks) and end of the network (sequence pooling).

**Comment by alihassanijr** [comment]
Hi @khawar512 
Can I please ask what repository or script from which your "original vit" code block is?
We based our Transformer Encoder Layer on Ross Wightman's timm package, and compared to ViT's original repository in JAX, and they're the same as far as I can tell: https://github.com/google-research/vision_transformer/blob/master/vit_jax/models.py#L90 .

**Comment by khawar512** [comment]
@stevenwalton thank you for your instant reply. Yes, I need your better advice and I will discuss it with you.
@alihassanijr I am using https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/vit.py repo for the implementation of ViTs.
If I will add dropouts and stochastic depth (drop path) code in the above repo, Will it be fine?

**Comment by alihassanijr** [comment]
I would assume so, because as far as I see everything else would be identical in theory, and I ran a sanity check just to be sure.

**Comment by khawar512** [comment]
Hi, @stevenwalton I am using the below link, and if you check the "Transformer" class which contains Attention and FeedForward is very simple. Would it be possible for you to align the only CCT Transformer class code like this? A separate python file is OK. I am doing some modifications which are not possible in your Transformer Class code (a class that contains Attention and FeedForward). Please help me out

https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/vit.py

**Comment by stevenwalton** [comment]
Hey, we're a bit confused what you actually want. If you want to make some modifications to CCT in vit-pytorch that should be relatively straight forward. You can make a fork, edit, and rebuild. Or you can just load the appropriate libraries/files. This would probably be the easiest. Then you could take the modules that we build and use them. You could also inherit [the main CCT class](https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/cct.py#L297) if you are just making minor modifications. I'm a bit confused though because our code is in a similar format to the rest of the library. The only differences is we added the ability to load pre-defined models (similar to how torchvision models work).

**Comment by stevenwalton** [comment]
Hey @khawar512 I'm going to close the issue. Please open it back up if you have more questions. Or feel free to email me.
