### ISSUE TITLE
pretrained on larger datasets on ImageNet?

### ISSUE THREAD

**Issue by RuohanZhang** [SHI-Labs/Compact-Transformers#19]
I saw the results on the ImageNet dataset have been published. Is this result pre-trained with additional datasets? What are the training parameters? Epoch, batch size?

**Comment by alihassanijr** [comment]
No, it is just trained on ImageNet. The models are trained for 300 epochs (+10 cooldown epochs), and 512 batch size. All the details are mentioned in the preprint.

**Comment by RuohanZhang** [comment]
Thank you very mach~
