### ISSUE TITLE
ViT-12/16 Imagenet weights

### ISSUE THREAD

**Issue by as3895** [SHI-Labs/Compact-Transformers#22]
Any plans on releasing the weights for the baseline ViT on imagenet?

**Comment by alihassanijr** [comment]
Hi,
Those were reported from the paper, and ViT was implemented in JAX. However you can refer to `timm` in which I believe some of the checkpoints were converted.

**Comment by as3895** [comment]
@alihassanijr : Thanks for the quick response. Would the evaluation script provided work for imagenet weights with minimal change (such as addition of dataset etc.)?

**Comment by alihassanijr** [comment]
It depends on the modifications, but in general it should. However, I would still recommend `timm`. The two scripts provided in this repo are very simple examples for quickly training and validating on CIFAR-10/100.

**Comment by alihassanijr** [comment]
I'm closing the issue now, if you still have questions feel free to open it back up.
