### ISSUE TITLE
interpolation of imagenet

### ISSUE THREAD

**Issue by Holidays1999** [SHI-Labs/Compact-Transformers#41]
Hi, sorry to trouble you again. I have successfully your results on cifar10, and I plan to reproduce the results on ImageNet.
I follow your configs for imagenet and my result is lower than yours about 2%.

I would like to know the interpolation's type used in your paper for imagenet.
As most paper's only use Bicubic, and your paper use "random" for imagenet.

Thanks very much!

**Comment by alihassanijr** [comment]
Hi,
I'm not sure if that's the issue here. Can you share your logs?
Also, can you verify your ImageNet copy's MD5?

**Comment by Holidays1999** [comment]
https://drive.google.com/file/d/1XuQTQtFKY2qZfMWJxzoPBOKZNYoqezAF/view?usp=sharing
Hi, I upload my log to google drive, I hope I can compare it with your log.
Thanks very much!

**Comment by alihassanijr** [comment]
I'm sorry, this log looks very different from the logs our training script provides. Are you using the same training script? Can you share the full command as well?

**Comment by Holidays1999** [comment]
Thanks, I have found the difference, for I make lr = batch_size *device_num / 512 * lr,
I will fix it and try again. Thanks for your help!
