### ISSUE TITLE
CIFAR10-100 image dataset

### ISSUE THREAD

**Issue by iliasprc** [SHI-Labs/Compact-Transformers#44]
Hello, I observed that your code loads image files from folders that are split in train/test. Did you convert the original files of CIFAR10/100 into jpg files ? I use this repo https://github.com/knjcode/cifar2png for the datasets.
Thanks in advance

**Comment by alihassanijr** [comment]
Hello, thank you for your interest.
No, we just added the torchvision CIFAR10 to the training script (not presently included in this repo, but it will be in the next).
Also, the latest version of `timm` supports TV datasets.

I'll be closing this issue now, but feel free it reopen it if you have further questions.
