### ISSUE TITLE
Training cct_7_7x2_224 on imagenet

### ISSUE THREAD

**Issue by iliasprc** [SHI-Labs/Compact-Transformers#46]
Hello,
have you tried to train this model on ImageNet?
I get only 45% accuracy with the same training hyperparameters as cct_14_7x2_224
thanks,
Ilias

**Comment by alihassanijr** [comment]
Hello,
Thank you for your interest. No we have not, as it is not designed for a dataset such as ImageNet, so I'm not surprised of this performance. It's not just that it has half the number of layers as CCT-14, it's that the number of channels, heads, and hidden dim are all very small.

I'll close this issue now, but feel free to follow up if you have any other questions.

**Comment by TIEHua** [comment]
> Hello, have you tried to train this model on ImageNet? I get only 45% accuracy with the same training hyperparameters as cct_14_7x2_224 thanks, Ilias

I also test the cct_7_7x2_224 on imagenet and achieve 70% top-1 accuracy.
