### ISSUE TITLE
pretrrain

### ISSUE THREAD

**Issue by cenchaojun** [SHI-Labs/Compact-Transformers#47]
thank you for your nice work, but i can't find pretrain model, could you tell me where i can find it.
best wish for you

**Comment by alihassanijr** [comment]
Hello,
Thank you for your interest. Could you specify which model you are referring to?
Most of our checkpoints are released and can be downloaded.

**Comment by stevenwalton** [comment]
@cenchaojun the checkpoints are located at the bottom of the repo's page under #Results. The accuracy number is a hyperlink that will download our checkpoints. You can also see all the pretrained models [here](https://ix.cs.uoregon.edu/~alih/compact-transformers/checkpoints/pretrained/)
