### ISSUE TITLE
What is config for 224 image size?

### ISSUE THREAD

**Issue by hadaev8** [SHI-Labs/Compact-Transformers#5]
How many image reductions should I have?
Is this right?
```
model = cct_7(img_size=im_size,
              num_classes=classes,
              positional_embedding='learnable',
              n_conv_layers=2,
              kernel_size=7,
              stride=2,
              padding=3,
              pooling_kernel_size=3,
              pooling_stride=2,
              pooling_padding=1)
```

**Comment by stevenwalton** [comment]
I think you can just change the hard coded value on main.py:95. We had it hard coded because the training script is only for CIFAR10. We haven't released everything in the code yet since we are still testing. 

I'll expose the option and reference the subsequent PR here.

**Comment by hadaev8** [comment]
Not clear for me what is tokenizer settings here
https://i.imgur.com/2FYkO8g.png
I mean kernel size, stride, pooling

**Comment by alihassanijr** [comment]
Kernel size is 3x3 in all our experiments (on small resolution sets like CIFAR and MNIST), with a 1x1 pad and 1x1 stride. Max pool kernel size is also 3x3, with a 1x1 pad, but with a 2x2 stride.

**Comment by hadaev8** [comment]
@alihassanijr whats for 224 resolution?

**Comment by alihassanijr** [comment]
We have not tried with that size specifically, but 7x7 should be fine.
