### ISSUE TITLE
Text Masked Attention: TextTokenizer.forward() should return "new_mask"

### ISSUE THREAD

**Issue by simonlevine** [SHI-Labs/Compact-Transformers#50]
Hello,

Love your work, it's coming in handy for deep learning on my NLP-like nucleotide data. In my use-case, I regularly pad sequences and in order to account for this padding, I would like to mask these "tokens" during the forward pass. However, when employing the masking tensor in the 'text' directory, I believe `TextTokenizer.forward()` should return the following (or similar):

` 
        return x, self.forward_mask(mask) if mask is not None else (x,mask)
`

By default, we return the argument `mask` rather than the tensor with the correct shape for the downstream mask required by the masked attention. This is OK for the embedding step as the forward step returns the same tensor (perhaps a bit of optimization could be of use here...), but this behavior causes errors in the tokenizer case.

I can make a PR if desired.

Again, thanks for your efforts. I have a few other questions but I'll save them for other issues.

**Comment by alihassanijr** [comment]
Hello,
Thank you for your interest, and bringing this to our attention.
I've started a PR for this issue. Can you confirm if it's what you expected. Also feel free to push your commits to the PR as well.

**Comment by simonlevine** [comment]
Hi,

Yes, looks good. Thanks
