### ISSUE TITLE
AttributeError: 'TransformerClassifier' object has no attribute 'num_tokens'

### ISSUE THREAD

**Issue by XiaominLi1997** [SHI-Labs/Compact-Transformers#53]
Hello, I got the error "AttributeError: 'TransformerClassifier' object has no attribute 'num_tokens'" when I use cct_7_7x2_224_sine and set pretrained=True

**Comment by alihassanijr** [comment]
Hello there,
Thank you for reporting this.
I'll start a PR to get this fixed.

**Comment by alihassanijr** [comment]
Can you confirm whether it's fixed now @XiaominLi1997

**Comment by XiaominLi1997** [comment]
> 
Hello, thanks for your modification, but there are still some errors, that is, mismatched params. 
![image](https://user-images.githubusercontent.com/25433111/150270175-5e7bbebe-94fd-40a6-9205-0f16ea004bd0.png)

**Comment by alihassanijr** [comment]
Are you modifying the image size? Can I see your run command?

**Comment by XiaominLi1997** [comment]
> Are you modifying the image size? Can I see your run command?
Yep, I use image size 224x224.
![image](https://user-images.githubusercontent.com/25433111/150275971-babb8edb-84c7-49af-989a-2426fdaa4007.png)

**Comment by alihassanijr** [comment]
I see. The latest merge should fix the issue.

**Comment by XiaominLi1997** [comment]
> I see. The latest merge should fix the issue.

Thx.
