### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by ireneb612** [SHI-Labs/Compact-Transformers#58]
Hi, I was wondering if I could use your finetuned model on my custom data! I already managed to run the Keras tutorial on my data, but I started from scratch! Is is possible to fine tune it? should I simply load your pretrained files? 

Thank you in advance

**Comment by stevenwalton** [comment]
We encourage you to try finetuning our model on your custom dataset. It will be possible to fine tune and load pretrained files but we can not guarantee that the features learned from our pretrained datasets (e.g. imagenet, cifar, flowers, etc) will be applicable to your dataset (see short discussion in our paper) and that you'll have good generalization.
