### ISSUE TITLE
Any intuitions on how to reduce Cuda Memory usage ?

### ISSUE THREAD

**Issue by Babars7** [SHI-Labs/Compact-Transformers#6]
I am working on applying cct_7 for another imgsize=128 example but my main problem is the CUDA Memory usage. Do you have any intuitions on parameters I could modify to reduce CUDA memory usage?  Thanks!

**Comment by alihassanijr** [comment]
Hi,

You can use bigger convolution windows. We used 3x3 convolutions for 32x32 images. You can change them to 5x5 (`--conv-size 5`) or even 7x7 (`--conv-size 7`). That should reduce the memory usage, but may have a slight performance impact.

**Comment by stevenwalton** [comment]
Along with what Ali said, you can try reducing the batch size. Also, you can try introducing gradient checkpointing into the model. Checkpointing trades computation time for memory (more computation time, less memory). Or using half precision (this is untested so if you do it we'd love to hear the results!). I wrote a little bit about both in [my blog](https://stevenwalton.github.io/tutorial/ml/cnn/2020/09/26/Checkpointing.html) (feedback welcome) but there's also a lot of material on both subjects that you should be able to find with some googling. 

Be warned though, depending how you checkpoint you may greatly increase your computation time (I suggest as little checkpointing as you can get away with) and half precision can make things unstable, so it is a bit trickier to tune.
