### ISSUE TITLE
Dino self-supervised vision transformer

### ISSUE THREAD

**Issue by seekingdeep** [SHI-Labs/Compact-Transformers#62]
@alihassanijr @stevenwalton @honghuis @Walleclipse @itsShnik
Hi there,

do you have any suggestions and thoughts regarding reducing the computational cost of [DINO](https://arxiv.org/abs/2104.14294).
can dino benefit from cct.

Demo of [Dino](https://huggingface.co/spaces/nielsr/DINO)

**Comment by stevenwalton** [comment]
I'm sorry, but this question is out of scope of the project. If you'd like to ask questions about CCT or our paper feel free to open a new issue but we are not supporting other works by other teams.
