### ISSUE TITLE
Training and evaluation scripts in examples folder

### ISSUE THREAD

**Issue by rmldj** [SHI-Labs/Compact-Transformers#67]
The `main.py` and `evaluate.py` scripts in the `examples/` folder got out of sync with the `cct_N` function definitions in `src/`, so there is an error when running them.

A quick fix would be to change L119 in `main.py` and L100 in `evaluate.py` from
```
model = models.__dict__[args.model](img_size=img_size,
```
to
```
model = models.__dict__[args.model]('custom', False, False, img_size=img_size,
```
Btw. thanks for a nice repository and nice paper!

**Comment by alihassanijr** [comment]
Thank you for your interest, and for bringing this to our attention.
