### ISSUE TITLE
”stochastic_depth“ should be "stochastic_depth_rate"

### ISSUE THREAD

**Issue by H-WU** [SHI-Labs/Compact-Transformers#7]
In lines 188, 223 and 266 of "cct.py", the”stochastic_depth“ should be "stochastic_depth_rate". So is the stochastic_depth_rate always 0.1?

**Comment by stevenwalton** [comment]
In our tuning we've found that a drop path rate of 0.1 gives good results. You are welcome to try other rates. We haven't exposed all hyperparameters yet as flags (paper is still in preprint) but will later. The current code will give some of our best results.

**Comment by alihassanijr** [comment]
Fixed: [82070a91](https://github.com/SHI-Labs/Compact-Transformers/commit/82070a91d3f71d23557e0d628a90accd770f493e)
