### ISSUE TITLE
colab notebook does not work

### ISSUE THREAD

**Issue by falseywinchnet** [SHI-Labs/Compact-Transformers#86]
The https://medium.com/pytorch/training-compact-transformers-from-scratch-in-30-minutes-with-pytorch-ff5c21668ed5

article written here provides a link to a colab that loads this github repository.
It fails with multiple errors- first, the cct_2 is not a valid option for model,
secondly, selecting any of the other models results in an error relating to multiple image sizes.
attempting to update this by following the instructions on the github and running the train.py file has the same result. 

I understand that a lot can change in three years but respectfully, none of the code I have pushed to my github repositories is in a state where it will not run.

It is a major replication crisis and infuriating to encounter code that cannot be run without fixing it.
Even those desirous of extending the work or trying new things will quickly give up if they encounter issues.

please revisit your work to ensure that someone who finds it will be able to run it.

**Comment by stevenwalton** [comment]
Thanks for the better attitude.

The colab has been fixed. If there are more errors please let us know.

You can also just clone the repo and things work more smoothly (only issue locally was a numpy deprecation).

> It is a major replication crisis and infuriating to encounter code that cannot be run without fixing it.
Even those desirous of extending the work or trying new things will quickly give up if they encounter issues.

Unfortunately [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell) is a real thing. The code will break again in the future without any action on our part. Software rots. 

We are in the business of generating **_research, not products_**. We are not selling you anything, we are not making money off of this, nor is it even remotely optimized. The replication is our description, the visibility of the code, and the checkpoints. If you are wishing to build upon our work, we are happy to hear that. But it does require that you understand what we did. We provide you a full paper with detailed explanation, and code that can be read even when the dependencies break beyond repair. This is beyond our control. We don't own pytorch, torchvision, numpy, and we certainly don't own HuggingFace and can buy out the `timm` package. Luckily we provide the weights which you are welcome to convert in any way you wish and will be generally future proof, I prefer [graftr](https://github.com/lmnt-com/graftr).
